# -*- coding: utf-8 -*-
"""BACKWARD CHAINING (profesi)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUNsY2XKRnirxx4vlMvjH_hDOXOgklJq
"""

def backward_chaining(goal, facts, rules):
  if goal in facts:
    return True

  for rule in rules:
    if rule["then"] == goal:
      if all(backward_chaining(cond, facts, rules) for cond in rule["if"]):
        return True
  return False

facts = ("likes_computers", "solves_problems", "likes_to_design")
rules = [
    {'if': {"likes_computers", "solves_problems"}, 'then': "should_be_engineer"},
    {'if': {"should_be_engineer", "likes_programming"}, 'then': "software_engineer"},
    {'if': {"should_be_engineer", "likes_to_design"}, 'then': "UI/UX_engineer"},
]

goal = "UI/UX_engineer"
result = backward_chaining(goal,facts, rules)
print(f"Is '{goal}' provable? ->", result)