# -*- coding: utf-8 -*-
"""SISTEM PAKAR 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUNsY2XKRnirxx4vlMvjH_hDOXOgklJq
"""

from experta import *

class Diagnosis(KnowledgeEngine):

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True))
  def flu(self):
    print("Diagnosis: You may have the Flu.")

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True))
  def pneumonia(self):
    print("Diagnosis: You may have Pneumonia.")

  @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False))
  def cold(self):
    print("Diagnosis:You may have a Common COld.")

  @Rule(Fact(sore_throat=True) & Fact(fever=True))
  def throat_infection(self):
    print("Diagnosis: You may have a Throat Infection.")

  @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False))
  def healthy(self):
    print("Diagnosis: You seem healthy.")

#TUGAS MENAMBAHKAN MINIMAL 4 PENYAKIT BARU
  @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(diarrhea=True))
  def stomach_flu(self):
    print("Diagnosis: Kamu mungkin mengalami Flu Perut atau Keracunan Makanan.")

  @Rule(Fact(chest_pain=True) & Fact(fatigue=True) & Fact(breathing_difficulty=True))
  def heart_problem(self):
    print("Diagnosis: Kamu mungkin mengalami masalah pada jantung.")

  @Rule(Fact(skin_rash=True) & Fact(sneezing=True) & Fact(runny_nose=True))
  def allergic_reaction(self):
    print("Diagnosis: Kamu mungkin mengalami Reaksi Alergi.")

  @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(sensitivity_to_light=True))
  def migraine(self):
    print("Diagnosis: Kamu mungkin mengalami Migrain.")

def get_input():
  """Helper function to get user input and convert to boolean (yes/no)."""
  def ask_question(question):
    return input(question + " (yes/no)): ").strip().lower() == "yes"

  return {
      "cough":ask_question("Do you have a cough?"),
      "fever":ask_question("Do you have a fever?"),
      "fatigue":ask_question("Do you feel tired or fatigued?"),
      "breathing_difficulty":ask_question("Do you have difficulty breathing?"),
      "sneezing":ask_question("Are you sneezing?"),
      "runny_nose": ask_question("Do you have a runny noyesse?"),
      "sore_throat": ask_question("Do you have a sore throat?"),
#MENAMBAHKAN 5 PERTANYAAN BARU
      "headache": ask_question("Apakah kamu mengalami sakit kepala?"),
      "nausea": ask_question("Apakah kamu merasa mual?"),
      "diarrhea": ask_question("Apakah kamu mengalami diare?"),
      "chest_pain": ask_question("Apakah kamu merasakan nyeri dada?"),
      "skin_rash": ask_question("Apakah kamu memiliki ruam pada kulit?"),
      "sensitivity_to_light": ask_question("Apakah kamu merasa silau atau sensitif terhadap cahaya?")
  }

#running the expert system
if __name__ == "__main__":
  symptons = get_input()
  engine = Diagnosis()
  engine.reset() # reset the knowledge engine

  for sympton, present in symptons.items():
    engine.declare(Fact(**{sympton: present}))

  engine.run() # run the inference engine