# -*- coding: utf-8 -*-
"""SISTEM PAKAR 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUNsY2XKRnirxx4vlMvjH_hDOXOgklJq
"""

from experta import *

class SistemPakarMedis(KnowledgeEngine):

  @Rule(Fact(demam=True) & Fact(batuk=True))
  def flu(self):
    print("Diagnosis: Flu.")

  @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
  def throat_infection(self):
    print("Diagnosis: Radang Tenggorokan.")

  @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
  def hernia(self):
    print("Diagnosis: Hernia. Innalillahi.")

#MENAMBAHKAN MINIMAL 4 PENYAKIT BARU
  @Rule(Fact(sakit_kepala=True) & Fact(tekanan_darah_tinggi=True))
  def hipertensi(self):
    print("Diagnosis: Hipertensi. Jaga pola makan ya.")

  @Rule(Fact(demam=True) & Fact(nyeri_sendi=True))
  def demam_berdarah(self):
    print("Diagnosis: Kemungkinan Demam Berdarah. Segera periksa ke dokter.")

  @Rule(Fact(batuk=True) & Fact(nyeri_dada=True))
  def bronkitis(self):
    print("Diagnosis: Bronkitis. Banyakin istirahat dan minum hangat.")

  @Rule(Fact(sakit_perut=True) & Fact(buang_air_besar_berdarah=True))
  def tukak_lambung(self):
    print("Diagnosis: Tukak lambung. Hindari makanan pedas dan asam.")


engine = SistemPakarMedis()
engine.reset()
engine.declare(Fact(batuk=True))
engine.declare(Fact(nyeri_dada=True))
engine.run()