# -*- coding: utf-8 -*-
"""Sistem Pakar (Forward Chaining, & Backward Chaining)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17f1MeiD7C84qkjjfFMewHMMbiwl-A_4T
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True))
  def flu(self):
    print("Diagnosis: You may have the Flu.")

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True))
  def pneumonia(self):
    print("Diagnosis: You may have Pneumonia.")

  @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False))
  def cold(self):
    print("Diagnosis:You may have a Common COld.")

  @Rule(Fact(sore_throat=True) & Fact(fever=True))
  def throat_infection(self):
    print("Diagnosis: You may have a Throat Infection.")

  @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False))
  def healthy(self):
    print("Diagnosis: You seem healthy.")

#TUGAS MENAMBAHKAN MINIMAL 4 PENYAKIT BARU
  @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(diarrhea=True))
  def stomach_flu(self):
    print("Diagnosis: Kamu mungkin mengalami Flu Perut atau Keracunan Makanan.")

  @Rule(Fact(chest_pain=True) & Fact(fatigue=True) & Fact(breathing_difficulty=True))
  def heart_problem(self):
    print("Diagnosis: Kamu mungkin mengalami masalah pada jantung.")

  @Rule(Fact(skin_rash=True) & Fact(sneezing=True) & Fact(runny_nose=True))
  def allergic_reaction(self):
    print("Diagnosis: Kamu mungkin mengalami Reaksi Alergi.")

  @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(sensitivity_to_light=True))
  def migraine(self):
    print("Diagnosis: Kamu mungkin mengalami Migrain.")

def get_input():
  """Helper function to get user input and convert to boolean (yes/no)."""
  def ask_question(question):
    return input(question + " (yes/no)): ").strip().lower() == "yes"

  return {
      "cough":ask_question("Do you have a cough?"),
      "fever":ask_question("Do you have a fever?"),
      "fatigue":ask_question("Do you feel tired or fatigued?"),
      "breathing_difficulty":ask_question("Do you have difficulty breathing?"),
      "sneezing":ask_question("Are you sneezing?"),
      "runny_nose": ask_question("Do you have a runny noyesse?"),
      "sore_throat": ask_question("Do you have a sore throat?"),
#MENAMBAHKAN 5 PERTANYAAN BARU
      "headache": ask_question("Apakah kamu mengalami sakit kepala?"),
      "nausea": ask_question("Apakah kamu merasa mual?"),
      "diarrhea": ask_question("Apakah kamu mengalami diare?"),
      "chest_pain": ask_question("Apakah kamu merasakan nyeri dada?"),
      "skin_rash": ask_question("Apakah kamu memiliki ruam pada kulit?"),
      "sensitivity_to_light": ask_question("Apakah kamu merasa silau atau sensitif terhadap cahaya?")
  }

#running the expert system
if __name__ == "__main__":
  symptons = get_input()
  engine = Diagnosis()
  engine.reset() # reset the knowledge engine

  for sympton, present in symptons.items():
    engine.declare(Fact(**{sympton: present}))

  engine.run() # run the inference engine

from experta import *

class SistemPakarMedis(KnowledgeEngine):

  @Rule(Fact(demam=True) & Fact(batuk=True))
  def flu(self):
    print("Diagnosis: Flu.")

  @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
  def throat_infection(self):
    print("Diagnosis: Radang Tenggorokan.")

  @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
  def hernia(self):
    print("Diagnosis: Hernia. Innalillahi.")

#MENAMBAHKAN MINIMAL 4 PENYAKIT BARU
  @Rule(Fact(sakit_kepala=True) & Fact(tekanan_darah_tinggi=True))
  def hipertensi(self):
    print("Diagnosis: Hipertensi. Jaga pola makan ya.")

  @Rule(Fact(demam=True) & Fact(nyeri_sendi=True))
  def demam_berdarah(self):
    print("Diagnosis: Kemungkinan Demam Berdarah. Segera periksa ke dokter.")

  @Rule(Fact(batuk=True) & Fact(nyeri_dada=True))
  def bronkitis(self):
    print("Diagnosis: Bronkitis. Banyakin istirahat dan minum hangat.")

  @Rule(Fact(sakit_perut=True) & Fact(buang_air_besar_berdarah=True))
  def tukak_lambung(self):
    print("Diagnosis: Tukak lambung. Hindari makanan pedas dan asam.")


engine = SistemPakarMedis()
engine.reset()
engine.declare(Fact(batuk=True))
engine.declare(Fact(nyeri_dada=True))
engine.run()

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True

  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred

facts = ("has_feathers", "has_beak", "carnivore")
rules = [
  {'if': {"has_feathers", "has_beak"}, 'then': "bird"},
  {'if': {"lays_eggs", "is_bird"}, 'then': "is_chicken"},
  {'if': {"cannot_fly", "is_bird"}, 'then': "is_penguin"},
  {'if': {"carnivore", "is_bird"}, 'then': "is_eagle"}
]

result = forward_chaining(facts, rules)
print("Inferred facts:", result)

def backward_chaining(goal, facts, rules):
  if goal in facts:
    return True

  for rule in rules:
    if rule["then"] == goal:
      if all(backward_chaining(cond, facts, rules) for cond in rule["if"]):
        return True
  return False

facts = ("likes_computers", "solves_problems", "likes_to_design")
rules = [
    {'if': {"likes_computers", "solves_problems"}, 'then': "should_be_engineer"},
    {'if': {"should_be_engineer", "likes_programming"}, 'then': "software_engineer"},
    {'if': {"should_be_engineer", "likes_to_design"}, 'then': "UI/UX_engineer"},
]

goal = "UI/UX_engineer"
result = backward_chaining(goal,facts, rules)
print(f"Is '{goal}' provable? ->", result)

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True

  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred

facts = ("has_wheels", "has_engine", "has_four_wheels")
rules = [
    {'if': {"has_wheels", "has_engine"}, 'then': "is_vehicle"},
    {'if': {"is_vehicle", "has_two_wheels"}, 'then': "is_motorcycle"},
    {'if': {"is_vehicle", "has_four_wheels"}, 'then': "is_car"},
  ]

result = forward_chaining(facts, rules)
print("Inferred facts:", result)

def backward_chaining(goal, facts, rules):
  if goal in facts:
    return True

  for rule in rules:
    if rule["then"] == goal:
      if all(backward_chaining(cond, facts, rules) for cond in rule["if"]):
        return True
  return False
facts = ("has_feathers, has_small_wings")
rules = [
    {'if': {"has_feathers", "has_feathers"}, 'then': "is_bird"},
    {'if': {"is_bird", "cannot_fly"}, 'then': "is_penguin"},
    {'if': {"has_small_wings"}, 'then': "cannot_fly"},
  ]
goal = "is_penguin"
result = backward_chaining(goal, facts, rules)
print(f"Is '{goal}' provable? ->", result)